# Generated by Django 5.2.4 on 2025-07-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='List of features for this plan'),
        ),
    ]
