# Generated by Django 5.2.4 on 2025-07-09 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionhistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='subscriptionplanchangelog',
            name='changed_by',
        ),
    ]
