# Generated by Django 5.2.4 on 2025-07-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_options_alter_member_alternate_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='area_or_locality',
            field=models.CharField(blank=True, help_text='Area, locality, or landmark for more granular location info.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='firm_name',
            field=models.CharField(blank=True, help_text='Company/organization/firm the member is associated with.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='referral_source',
            field=models.CharField(blank=True, help_text='How did the member hear about the gym?', max_length=100, null=True),
        ),
    ]
