# Generated by Django 5.2.4 on 2025-07-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_area_or_locality_member_firm_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='referral_source',
            field=models.CharField(blank=True, choices=[('Friend', 'Friend'), ('Social Media', 'Social Media'), ('Flyer', 'Flyer'), ('Online Ad', 'Online Ad'), ('Other', 'Other')], help_text='How did the member hear about the gym?', max_length=20, null=True),
        ),
    ]
